### ISSUE TITLE
64bit only

### ISSUE THREAD

**Issue by githluapb** [orgua/universal-android-debloater-UI#1]
Currently, dearpygui is 64bit-only, so I can not use my old pi-driven linux to test the gui - and I am so eager to..
Any plans to or ideas how to make the gui 32bit compatible?

**Comment by orgua** [comment]
didn't noticed that :( seems like an edge-case though. Well I won't move to yet another UI-Framework soon - but am thinking about an improved CLI (in comparison to the UAD-bash)
btw: virtualbox does a great job at keeping your main system clean.

**Comment by githluapb** [comment]
Tried another system, opengl problem. Virtualbox did the job to start uad-ui, but I have another problem, see thread: https://github.com/orgua/universal-android-debloater-UI/issues/2
