### ISSUE TITLE
from dearpygui import core, simple error

### ISSUE THREAD

**Issue by Si-kaR** [orgua/universal-android-debloater-UI#4]
Hi
First time attempting to use Universal Debloatware package on fedora

I following the instructions here  however the final command returns the error that follows the commands. 
sudo apt install python3-pip  
sudo apt install git

git clone https://github.com/orgua/universal-android-debloater-UI.git
cd universal-android-debloater-UI

pip install -r requirements.txt

py main_gui.py

Traceback (most recent call last):
  File "/home/griphen/universal-android-debloater-UI/main_gui.py", line 1, in <module>
    from dearpygui import core, simple
ImportError: cannot import name 'core' from 'dearpygui' (/home/griphen/.local/lib/python3.11/site-packages/dearpygui/__init__.py)

Any help? I really need to debloat my phone 😂😂😂

**Comment by Si-kaR** [comment]
In short, I get the error below when I run py main_gui.py


ImportError: cannot import name 'core' from 'dearpygui' (/home/griphen/universal-android-debloater-UI/venv/lib64/python3.9/site-packages/dearpygui/__init__.py)

**Comment by orgua** [comment]
I should delete this repo. The main project is no longer maintained, because they started over [completely new](https://github.com/0x192/universal-android-debloater). At least they have their own gui now and took my design.
